version: '3.9'
services:
  mysql:
    image: mysql:8
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sip
    networks:
      - sip-net
  sip:
    container_name: sip
    build:
      context: .
      dockerfile: Dockerfile
    image: sip:latest
    ports:
      - '8080:8080'
    networks:
      - sip-net
networks:
  sip-net:
    name: sip-net
