spring:
    datasource:
        url: jdbc:mysql://mysql:3306/sip?useSSL=false&&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: validate
